# Generated by Django 4.2.5 on 2023-09-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
